# markdown: GFM
# title: awesome-topics
# markdown: kramdown

# kramdown:
#   input: GFM
#   math_engine: mathjax
#   syntax_highlighter: rouge

# theme: minima
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - jemoji
