# markdown: GFM
# title: awesome-topics
# markdown: kramdown

# kramdown:
#   input: GFM
#   math_engine: mathjax
#   syntax_highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  hard_wrap: false
  syntax_highlighter: rouge

theme: minima

plugins:
  - jemoji
